import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Auth",
    description: "Generated By Create Next App",
};

export default function AuthLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="bg-dark-1 flex items-center justify-center min-h-screen">
            {children}
        </div>
    );
}
